#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - python-virtualenv

runcmd:
    - mkdir /home/ubuntu/tmp
    - git clone https://github.com/Iprenen/projectcloudcomp.git
    - mkdir /home/ubuntu/messaging
    - mkdir /home/ubuntu/messaging/geo
    - mkdir /home/ubuntu/messaging/msh
    - mv projectcloudcomp home/ubuntu/messaging
    - cd /messaging
    - virtualenv --no-site-packages venv
    - source venv/bin/activate
    - pip install celery
    - sudo -H -u ubuntu bash -c "celery worker -A calculate &"

