#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - python-virtualenv
    - rabbitmq-server
    - gmsh libmed1
    - libdolfin-lib

runcmd:
    - mkdir /home/ubuntu/tmp
    - git clone https://github.com/Iprenen/projectcloudcomp.git
    - mkdir /home/ubuntu/messaging
    - mkdir /home/ubuntu/messaging/geo
    - mkdir /home/ubuntu/messaging/msh
    - mv projectcloudcomp home/ubuntu/messaging
    - cd /messaging
    - virtualenv --no-site-packages venv
    - source venv/bin/activate
    - pip install Flask
    - pip install celery
    - pip install flower
    - curl -s http://fenicsproject.org/fenics-install.sh | bash

